# --- Basic options --- #

# Name of website
title: Journal de bord

# Short description of your site
description: de Mathématiques au CSJA

# Your name to show in the footer
author: Nizar MOUSSATAT

# --- List of links in the navigation bar --- #

navbar-links:
   à propos : "aboutme"
   Blog: "/blog/"
   Oldies :
    - 1ère S : "/classes/1s"
   Au collège :
    - Quatrième B: "/classes/4b"
    - Troisième C: "/classes/3c"
   Au lycée :
    - Seconde B : "/classes/2b"
    - Seconde C : "/classes/2c"
    - SNT : "/classes/snt"

# --- Logo --- #
# title-img: /path/to/image

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour here.
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: /path/to/image


# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  email: "nizar.moussatat@ac-grenoble.fr"
#  facebook: nizar.moussatat
  github: moussatat
  twitter: zenxbear
#  rss: true
#  reddit: zenxbear
#  linkedin: moussatat
#  xing:  
#  stackoverflow: "3943160/zenxbear"
#  snapchat: zenxbear
#  instagram: zenxbear
#  youtube: user/zenxbear
#  spotify: 
#  telephone: 
#  steam: zenxbear
#  twitch: zenxbear
#  yelp:  
#  telegram:  


# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
#  linkedin: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "moussatat.github.io"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Colours / background image --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#ede7d5" #for TUFTE, default is "#F5F5F5" 
navbar-text-col: "#404040" # for TUFTE, default is  "#404040"
navbar-children-col: "#ede7d5" #for TUFTE, default is "#F5F5F5"
page-col: "#fffff8" #for TUFTE, default is "#FFFFFF"
link-col: "#a00000" # for TUFTE, default is "#008AFF"
hover-col: "#0085A1"
footer-col: "#ede7d5" #for TUFTE, default is "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#a00000" # for TUFTE, default is  "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-151428459-1"

# Fill in your Google Analytics ID to track your website using GA
# google_analytics: "UA-151428459-1"

# Google Tag Manager ID
# gtm: "GTM-58KGCDS"

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: "2767515569980352"

# To use Staticman comments, uncomment the following section and fill in
# "repository", "branch", and "endpoint".
# If you want to use reCaptcha for staticman (optional for spam protection), then fill
# in the "siteKey" and "secret" parameters below and also in `staticman.yml`.
staticman:
  repository : moussatat/moussatat.github.io # GitHub username/repository eg. "moussatat/moussatat.github.io" https://staticman3.herokuapp.com/v3/connect/github/moussatat/moussatat.github.io/
  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL, but recommended for spam protection)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>
    
    
# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances


# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
# date_format: "%B %-d, %Y"
date_format: "%-d %B %Y"

future: true

# Facebook App ID
#fb_app_id: ""

 
 
# Build settings
markdown: kramdown
 
# ---    --- #
timezone: "Europe/Paris"
markdown: kramdown
#highlighter: rouge

#permalink: /:year-:month-:day-:title/
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 5
  
kramdown:
    # Auto-generate ID's for headings
    auto_ids: true
    input: GFM
    math_engine: mathjax 
    syntax_highlighter: rouge
highlighter: rouge

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts 
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true


# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap  
  
# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
